services:
  - type: web
    name: yt-midi-server
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
