services:
  - type: web
    name: yt-midi-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python yt-midi-server/app/main.py
    plan: free
    autoDeploy: true
